### PR TITLE
Pin pytest>=5.3.1,<5.4.0

### LINKED ISSUE #39: CI tests failing
https://github.com/exercism/python-test-runner/runs/876457035?check_suite_focus=true#step:4:28

### PR DESCRIPTION
**Pull request by cmccandless**
Resolves #39

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -8,4 +8,4 @@ COPY . /opt/test-runner
 
 WORKDIR /opt/test-runner
 
-ENTRYPOINT [ "sh", "bin/run.sh" ]
+ENTRYPOINT [ "sh", "bin/run.sh", "-v" ]
```
Comment (cmccandless) [inline Dockerfile:11]:
```suggestion
ENTRYPOINT [ "sh", "bin/run.sh" ]
```

File: bin/run-in-docker.sh [hunk 2]
```diff
@@ -36,4 +36,4 @@ mkdir -p "$output_dir"
 docker run \
     --mount type=bind,src=$PWD/$2,dst=/solution \
     --mount type=bind,src=$PWD/$output_dir,dst=/output \
-    python-test-runner $1 /solution/ /output/
+    python-test-runner $1 /solution/ /output/ -v
```
Comment (cmccandless) [inline bin/run-in-docker.sh:39]:
```suggestion
    python-test-runner $1 /solution/ /output/
```

**Comment by cmccandless** [comment]
Maintainer note: please, PLEASE **squash-merge** this when changes are done.

**Comment by cmccandless** [comment]
Going to merge this, and make another issue to investigate what changed in 5.4.0 that broke the test-runner.
